### PR TITLE
Bugfix/raic 42 legacy os export different than edit show record vod

### PR DESCRIPTION
**Pull request by britaumich**
I added serial number and tdx_tickets to the export CSV function.
Please look at the headers' format and devices and tickets display. I am not sure what is the best way to do that.
To add serials to the CSV file I created the display_hostname_serial method in the Device model displaying 'none' if a hostname or serial is not present.
I put all tdx tickets into one field separating them with " ; "

### CODE REVIEW

**Review by rsmoke — CHANGES_REQUESTED** [review]
One item in the JIRA ticket was to show the **Serial number** (if present) in the 'Show' page for the record (ie. host/legacy_os_records/386) Would you add that as a display item on the show pages for each record type that include a device.

**Comment by britaumich** [comment]
Well, did not read the ticket carefully...
Should we then change the device's display_name back to [hostname - serial]? We had that from the beginning, but (I believe) Nikki asked us to show hostname only. Or should we display two fields: hostname and serial?

**Comment by rsmoke** [comment]
The two fields is probably clearer

-

Rick Smoke, Application Architect

For assistance please submit a request at:
https://lsa.umich.edu/technology-services/help-support.html

College of Literature, Science, and the Arts | University of Michigan
LSA Technology Services | 301 East Liberty Street, Ann Arbor, MI 48109

**Review by rsmoke — APPROVED** [review]
By the powers vested in me I approve this!

**Pull request merged**
