### PR TITLE
LRA-821-update-ruby-version-to-3-3

### PR DESCRIPTION
**Pull request by britaumich**
Ruby version was updated to 3.3.0.
Also I had to add [gem 'psych', '< 4'] to the Gemfile, because of the error described here: [Unknown alias: default (Psych::BadAlias)](https://stackoverflow.com/questions/71191685/visit-psych-nodes-alias-unknown-alias-default-psychbadalias)
Ruby 3.0 comes with Psych 3, while Ruby 3.1+ comes with Psych 4.
The problem is fixed in Rails 7.

### CODE REVIEW

**Comment by rsmoke** [comment]
I pulled this branch down and it would not run on my local machine. Now when I checkout master, it also does not run. 🤔

**Comment by britaumich** [comment]
@rsmoke What are your errors?
I had to install mysql2 gem with the following command to run even the master (because I couldn't install ruby 3.0.1 I had to make it run with ruby 3.1.0):

```gem install mysql2  -v '0.5.5' -- --with-mysql-lib=$(brew --prefix mysql)/lib --with-mysql-dir=$(brew --prefix mysql) --with-mysql-config=$(brew --prefix mysql)/bin/mysql_config --with-mysql-include=$(brew --prefix mysql)/include --with-ldflags="-L$(brew --prefix zstd)/lib -L$(brew --prefix openssl)/lib -L$(brew --prefix zlib)/lib" --with-cppflags="-I$(brew --prefix openssl)/include -I$(brew --prefix zlib)/include"```

**Comment by britaumich** [comment]
@rsmoke Do you have a VPN running?

**Review by rsmoke — APPROVED** [review]
@britaumich Finally fixed the webpacker stuffs

**Pull request merged**
