### PR TITLE
Append_to_notification_tweaks

### PR DESCRIPTION
**Pull request by rsmoke**

### CODE REVIEW

**Review by britaumich — COMMENTED** [review]
What does this scope change?
scope :active, -> { where('closedate > ?', DateTime.now).order(:opendate) }

We check it here anyway:
<% Notification.active.each do |nt| %>
  <% if (nt.opendate..nt.closedate).cover? DateTime.now %>

And since you decided to edit this files: I think this loop [Notification.active.each do] (or [Notification.all.each do]) doesn't make sense because we can have only one notification that will satisfy availability validation. Is this correct?

**Comment by rsmoke** [comment]
> What does this scope change?
> scope :active, -> { where('closedate > ?', DateTime.now).order(:opendate) }
> 
> We check it here anyway:
> <% Notification.active.each do |nt| %>
> <% if (nt.opendate..nt.closedate).cover? DateTime.now %>
> 
> And since you decided to edit this files: I think this loop [Notification.active.each do] (or [Notification.all.each do]) doesn't make sense because we can have only one notification that will satisfy availability validation. Is this correct?

The scope adds a listing of only active item (items that are going open and/or have not closed yet) that are to be displayed with the addition of being able to order the returned result by opendate for the dashboard. Now that you point out the second conditional √  it is not necessary for the purpose of the partial. I'll remove it.

**Review by britaumich — CHANGES_REQUESTED** [review]
Could you please add that scope to partials/notification too

**Comment by rsmoke** [comment]
> Could you please add that scope to partials/notification too

uhuh, i will, I did, it's done.

**Review by britaumich — APPROVED** [review]
Well, I think now all is better, good, great

**Pull request merged**
