### PR TITLE
Lra 75 add auditing action role access

### PR DESCRIPTION
**Pull request by britaumich**
Here is a new Audit action for a dpa_exceptions table record.
The action is authorized. 
Access is controlled by the access_lookup table. 
The audit log view might be changed (styles, format)
If you approve it we can add it to all tables.

### CODE REVIEW

**Review by rsmoke — COMMENTED** [review]
I will swap in display_name for the areas that only display a record ID

**Comment by britaumich** [comment]
Added check: if a user still exists then display user_name_email else user_id (commit 16bbb5d)
Added ugly manual if-else method to display Data Type name instead of id (commit 81bb359) ??????

**Review by rsmoke — COMMENTED** [review]
This looks good so far, I am troubleshooting the  sort order for the audit recored set

**Review by rsmoke — COMMENTED** [review]
good so far

**Comment by britaumich** [comment]
Cool!

**Pull request merged**
