### PR TITLE
add zip files toacceptable_types

### PR DESCRIPTION
**Pull request by britaumich**
Zip files were added to the list f file allowed to upload to all four main tables.

### CODE REVIEW

**Review by anantaUM — COMMENTED** [review]
**Questions**:
1) How did you decide on the list of zip content type ?
2) Are we sure we did not miss any content type ?
3) What are the different file extensions did you test with this code ?

**Comment by britaumich** [comment]
1. I took zip MIME types from here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
2. No, I am not sure. We'll find that if they try to upload a file that is not in that list
3. I tested zip, bzip, bzip2, gzip. Did not test x-7z-compressed, because 7z is a Windows compress command.

**Review by anantaUM — APPROVED** [review]

**Comment by anantaUM** [comment]
Please ask someone with windows machine to test '**x-7z-compressed'** file format. Thanks.

**Comment by dschmura** [comment]
I think the code looks good. What are the ways to test?

**Comment by britaumich** [comment]
@dschmura I deployed it into the production server already, since Ananta approved it. You can go there, create a test record and upload a zip file. Or test it on your local host.

**Pull request merged**
